### ISSUE TITLE
Crash when jetpack activated

### ISSUE THREAD

**Issue by kronflux** [DeadMG/puppy-jetpack-ui#1]
It's only happened once so far, otherwise working properly but I activated my jetpack and got this crash:

> 36789.062 Error MainLoop.cpp:1284: Exception at tick 28000030: The mod Puppy's Jetpack UI (0.1.6) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event puppy-jetpack-ui::on_nth_tick(5)
> __puppy-jetpack-ui__/script/gui.lua:152: attempt to index local 'fuel' (a nil value)
> stack traceback:
> 	__puppy-jetpack-ui__/script/gui.lua:152: in function <__puppy-jetpack-ui__/script/gui.lua:127>
> 36789.062 Error ClientMultiplayerManager.cpp:99: MultiplayerManager failed: "The mod Puppy's Jetpack UI (0.1.6) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event puppy-jetpack-ui::on_nth_tick(5)
> __puppy-jetpack-ui__/script/gui.lua:152: attempt to index local 'fuel' (a nil value)
> stack traceback:
> 	__puppy-jetpack-ui__/script/gui.lua:152: in function <__puppy-jetpack-ui__/script/gui.lua:127>"
> 36789.062 Info ClientMultiplayerManager.cpp:610: UpdateTick(28000030) changing state from(InGame) to(Failed)
> 36794.353 Info ClientMultiplayerManager.cpp:211: Quitting multiplayer connection.
> 36794.353 Info ClientMultiplayerManager.cpp:610: UpdateTick(28000030) changing state from(Failed) to(Disconnected)
> 36795.350 Info UDPSocket.cpp:218: Closing socket
> 36795.350 Info UDPSocket.cpp:248: Socket closed
> 36796.827 Quitting: user-quit.
> 36797.110 Steam API shutdown.
> 36797.117 Goodbye

**Comment by DeadMG** [comment]
This was fixed some time ago
